### ISSUE TITLE
The commands insert the original text and not the translation

### ISSUE THREAD

**Issue by MelodyDuplaix** [pkhr/obsidian-inline-translate#1]
I set the target language to`fr`.
But, when I use the commands, regardless of the starting language, the text obtained is the same as the starting text, in the same language.
I also tried to change the target language to `en` but it's changed nothing.
![image](https://github.com/user-attachments/assets/69077045-1bca-458a-9831-ab00ce200d23)
![image](https://github.com/user-attachments/assets/6d5bdfb1-d338-46dd-a6cd-70ebd6d03237)
![image](https://github.com/user-attachments/assets/b91f58a0-141f-4b3c-b6fa-cca958906fae)

**Comment by pkhr** [comment]
This should be fixed in 0.1.1 - just pushed it

**Comment by MelodyDuplaix** [comment]
I'm sorry, but I updated it to 0.1.1, and it don't work either. It still displays the original text and not the translated text.

**Comment by pkhr** [comment]
Let me check it right now.

**Comment by pkhr** [comment]
Could you check if it works for you if you clear out "Preferred languages" and keep Target language as "fr"?

**Comment by MelodyDuplaix** [comment]
Yes, I confirm that, when I remove the preferred languages, it works. Thanks

**Comment by pkhr** [comment]
Great that it works for you! And thank you that you have pointed that out! I'll make the fix to make sure it works without this issue. Hope you find this useful!
